import = [
  "~/.config/alacritty/themes/themes/catppuccin_latte.toml",
]

[window]
opacity = 1
decorations = "Full"

[font]
normal = { family = "FiraCodeNerdFontMono", style = "Regular" }
bold = { family = "FiraCodeNerdFontMono", style = "Regular" }
italic = { family = "FiraCodeNerdFontMono", style = "BoldItalic" }
size = 11

